---
gleaner:
  summon: true # do we want to visit the web sites and pull down the files
  mill: true
  runid: RUNIDHERE # this will be the bucket the output is placed in...
millers:
  mock: false
  graph: true
  spatial: true
  shacl: true
  organic: false
  tika: false
  fdptika: false
  fdptikajena: false
  fdpgraph: false
  prov: false
sources:
- name: localhost:9090  # domain with all .s removed your.domain.org -> yourdomainorg
  shortname: localhost:9090 # any short name you wish (one word, no spacing)
  logo: http://geodex.org/images/logos/EarthCubeLogo.png
  url: http://localhost:9090/ieda-sitemap.xml
  headless: false
  sitemapformat: xml
  active: true
